version: "3.3"

services:
  ping:
    image: lestokil/ping:latest
    ports:
      - 8090:8090
    environment:
      - RABBIT_HOST=rabbitmq
      - RABBIT_USER=admin
      - RABBIT_PASSWORD=admin
    networks:
      - pingpong_shared

  pong:
    image: lestokil/pong:latest
    ports:
      - 8082:8082
    environment:
      - RABBIT_HOST=rabbitmq
      - RABBIT_USER=admin
      - RABBIT_PASSWORD=admin
    networks:
      - pingpong_shared

networks:
  pingpong_shared:
    external:
      name: docker_pingpong_shared
