FROM maven:3.6.1-jdk-11-slim AS build
COPY ./ ./
RUN mvn clean package -pl ping -am -DskipTests

FROM openjdk:11-jdk-slim
MAINTAINER lestokil
COPY --from=build /ping/target/ping-0.0.1-SNAPSHOT.jar /ping.jar
CMD ["java", "-jar", "/ping.jar"]
EXPOSE 8090
